-- task_2.sql
-- CREATE TABLES FOR alx_book_store

USE alx_book_store;

CREATE TABLE AUTHORS (
    AUTHOR_ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    COUNTRY VARCHAR(50)
);

CREATE TABLE BOOKS (
    BOOK_ID INT PRIMARY KEY,
    TITLE VARCHAR(200),
    AUTHOR_ID INT,
    PRICE DECIMAL(10,2),
    PUBLICATION_YEAR YEAR
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    ADDRESS VARCHAR(255)
);

CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    ORDER_DATE DATE
);

CREATE TABLE ORDER_DETAILS (
    ORDER_DETAIL_ID INT PRIMARY KEY,
    ORDER_ID INT,
    BOOK_ID INT,
    QUANTITY INT
);
